apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: inference-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
